### ISSUE TITLE
Install problems..

### ISSUE THREAD

**Issue by zacforsman** [chollenbeck/rad_haplotyper#23]
I'm having trouble installing the perl modules on my Ubuntu server following your instructions.. I tried several alternative ways of installing the perl modules and many of them worked but the script won't run.  I second Jon's suggestion of a miniconda installation... I've been fighting with this for hours.  Thanks.  -Zac

**Comment by zacforsman** [comment]
On Ubuntu, the packages wouldn't install with `cpan Perl::Module`, instead `cpan install VCF` (all caps) worked for all modules.  However when I run  
`rad_haplotyper.pl ` I get the following error: 
```
Undefined value assigned to typeglob at /usr/lib/x86_64-linux-gnu/perl5/5.22/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /usr/lib/x86_64-linux-gnu/perl5/5.22/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /usr/lib/x86_64-linux-gnu/perl5/5.22/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /usr/lib/x86_64-linux-gnu/perl5/5.22/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /usr/lib/x86_64-linux-gnu/perl5/5.22/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /usr/lib/x86_64-linux-gnu/perl5/5.22/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /usr/lib/x86_64-linux-gnu/perl5/5.22/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /usr/lib/x86_64-linux-gnu/perl5/5.22/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /usr/lib/x86_64-linux-gnu/perl5/5.22/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /usr/lib/x86_64-linux-gnu/perl5/5.22/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /usr/lib/x86_64-linux-gnu/perl5/5.22/List/MoreUtils.pm line 94.
Undefined value assigned to typeglob at /usr/lib/x86_64-linux-gnu/perl5/5.22/List/MoreUtils.pm line 94.
Could not find sub 'uniq' exported by List::MoreUtils at /home/z/programs/rad_haplotyper.pl line 8.
BEGIN failed--compilation aborted at /home/z/programs/rad_haplotyper.pl line 8.
```

According to the perl documentation: 

```
Undefined value assigned to typeglob
        (W misc) An undefined value was assigned to a typeglob, a la "*foo =
        undef". This does nothing. It's possible that you really mean "undef
        *foo".
```

Any suggestions on how to install would be most welcome.  -Zac

**Comment by chollenbeck** [comment]
Hi Zac,

What errors did you get when you tried to install the modules with cpan? I don't think I've had a problem with these particular modules on Ubuntu. For example, what error do you get when you run:

`cpan List::MoreUtils`

**Comment by zacforsman** [comment]
I get a permissions denied error, unless I do `sudo cpan
List::MoreUtils`...oddly, now when I enter `rad_haplotyper.pl` I get the
help message!  It suddenly looks like it works!  Thanks for the help. -Zac

----------------------------------
Zac H. Forsman,  Ph.D.
Researcher, Hawaii Institute of Marine Biology
46-007 Lilipuna Rd, Kaneohe, HI 96744 (Fedex or deliveries)
Google Scholar profile:
https://scholar.google.com/citations?hl=en&user=MyhFvt4AAAAJ

**Comment by chollenbeck** [comment]
Great - glad you got it to work.
