### ISSUE TITLE
Feature request: phased vcf

### ISSUE THREAD

**Issue by SheaML** [chollenbeck/rad_haplotyper#27]
I'm hoping this might be a simple request. I'd like an output .vcf that retains information on phase.

I can see that there is already a sub-routine for this, but the comment says "not currently supported". 

I tried the sub-routine, and it seemed to give a phased vcf file. 

Just wondering what, if any issues I may encounter trying if I try to use this file. 

Thanks,
Shea

**Comment by chollenbeck** [comment]
I had kept that from being a supported output type because I hadn't done very extensive testing with it. You might try it with a few loci and manually check the results.

**Comment by SheaML** [comment]
Thanks Chris, I will let you know if I discover any issues with the file.
