### ISSUE TITLE
Script runs but no output files

### ISSUE THREAD

**Issue by baileyjc** [chollenbeck/rad_haplotyper#34]
Hello,

I tried running rad_haplotyper.pl on my data and it works but there are no output files.

Here is my code for running the script:
rad_haplotyper.pl -v SNP.DP3g95p5maf05.HWE.recode.vcf -r reference.fasta -g SNP.recode.genepop -a SNP.recode.ima -p SNP.recode.popmap

These are the last two lines I get after all SNPs have been collapsed into haplotypes and everything is filtered:
Writing Genepop file: SNP.recode.genepop
No such file or directory at rad_haplotyper.pl line 946.

I checked line 946 which mentions a folder named POP, so I created a folder named POP and ran the code again but it still didn't create any output files.

Any help is appreciated! Thanks

**Comment by sjoleary** [comment]
Based on my experience, I suspect this has to do with `rad_haplotyper` not being able to find your `popmap` (from your line of code above `-p SNP.recode.popmap`). I've had this happen where I had a typo in my filename.

**Comment by baileyjc** [comment]
I have the popmap file in the same folder but isn't the "-p SNP.recode.popmap" naming the output files? My popmap file name is popmap.

**Comment by pdimens** [comment]
`-p` should be specifying your popmap file

**Comment by baileyjc** [comment]
Ah, well that solves it. My apologies but thank you for your time!
